### ISSUE TITLE
Could not find board y offset

### ISSUE THREAD

**Issue by WallK** [laelath/hack-match-bot#1]
I'm running your bot in VM and all I get in the output is this (**Could not find board y offset** repeats)
```
Finding EXAPUNKS window
Validating window parameters
Could not find board y offset
```
I tried 1080p fullscreen and 1920*1080 window.
What can I do to help find what is causing this?
Thanks

**Comment by laelath** [comment]
First, did you also disable the CRT effect? Second would be that you have to start hack match before starting the bot (as in hit start on the hack match screen, it doesn't do any menu navigation).

**Comment by WallK** [comment]
Yes, I did disable CRT distortion. And yes, I started script after the game was playing (blocks descending on a player).

**Comment by laelath** [comment]
Try turning vsync on/forcing it on, tearing would sometimes cause issues with reading the screen. Otherwise I'm at a loss as to why it's not working.

**Comment by laelath** [comment]
I rewrote the X11 code of the program, that might have done something magical to make it work. It not finding the board y offset means that it didn't detect any blocks in the screenshot of the game it took. This could mean that the screen grabbing silently failed, or that there is something that is causing the colors to be a bit different (things like redshift don't affect it since I grab the screen straight from EXAPUNKS). I have run it with a Nvidia and Intel GPUs and the exact color matching worked on both so I thought that exact color matching would work across graphics vendors.
